### PR TITLE
Adding example for ESPHome

### PR DESCRIPTION
**Pull request by stgtroman**
Bug fix:
setNewI2CAdr(): added missing bit shifting.

### CODE REVIEW

**Comment by stgtroman** [comment]
Hi Christian, 
I've setup a multisensor project with your sensors on ESPHome.
I want to participate you and created a small example (reduced function set out of my own source code).

During my tests I used the Arduino example to give new addresses to my sensors and found a bug.

Greets,
Roman

**Comment by BeFlE** [comment]
Hi Roman,

thanks for the bugfix.
I am very happy that you share your project with us. 

Many greetings 
Christian

**Comment by Parateam** [comment]
Hi Roman, i use 6 sensors with your code from the example. It works after chanches the adresses with the MQTT firmware first. 

I have a question: How to start the voids to change the values for wet and dry with esphome code? Or read out the values.

Could you add it to the example?

Thanks 
Peter from Munich

**Comment by stgtroman** [comment]
Hey Peter,

I still have issues sending dynamic data during runtime. When I find some time, I will look into it again.

Do you already know the values your sensors should have? Then I could add that in the constructor.

Greets,
Roman from Mutlangen

**Pull request merged**
